language: cpp

git:
  depth: 1000

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8.1
  fast_finish: true

addons:
  artifacts:
    paths:
      - $(ls powershell*{deb,pkg,AppImage,gz} | tr "\n" ":")
      - pester-tests.xml

install:
  # Default 2.0.0 Ruby is buggy
  # Default bundler version is buggy
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      rvm install ruby-2.3.3;
      rvm --default use 2.3.3;
    fi
  - pushd tools
  - ./install-powershell.sh
  - popd
  # spellcheck
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      nvm install 6.4.0 &&
      npm install -g markdown-spellcheck@0.11.0;
    fi
  - ulimit -n 4096
  - pwsh -File tools/travis.ps1 -Stage Bootstrap

script:
  - pwsh -File tools/travis.ps1
  # spellcheck
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      mdspell '**/*.md' '!powershell/**/*.md' --ignore-numbers --ignore-acronyms --report;
    fi

after_failure:
  - pwsh -File tools/travis.ps1 -Stage Failure

after_success:
  - pwsh -File tools/travis.ps1 -Stage Success
