version: 6.0.0-alpha.17-{build}

image: Visual Studio 2015

cache:
  - '%LocalAppData%\Microsoft\dotnet'
  - '%HOMEDRIVE%%HOMEPATH%\.nuget\packages'

nuget:
  project_feed: true

install:
  - git submodule update --init
  - ps: Import-Module .\tools\Appveyor.psm1
  - ps: Invoke-AppveyorInstall

build_script:
  - ps: Invoke-AppveyorBuild

test_script:
  - ps: Invoke-AppveyorTest

after_test:
  - ps: Invoke-AppVeyorAfterTest

on_finish: 
  - ps: Invoke-AppveyorFinish
